when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        excluded_ajax_paths: '^/(api)/'

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false