services:
  - type: web
    name: video-platform-api
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: video-platform-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: "*"
      - key: JWT_PASSPHRASE
        generateValue: true

databases:
  - name: video-platform-db
    plan: free
    databaseName: video_platform
    user: video_user